version: '3.4'

services:
  envoy:
      image: envoy
      build:
        context: .
        dockerfile: ./envoy/Dockerfile
      ports:
        - 8090:8090
  angularioexample:
    image: angularioexample
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200